language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x

before_install:
  - go get github.com/nsqio/go-nsq
  - go get gopkg.in/gcfg.v1
  - go get github.com/0xef53/nsq-consumer

install:
  - go get -v -tags netgo -ldflags '-s -w' ./...

notifications:
  email:
    - sergey@divpro.ru
